#!/bin/sh
# Lease DHCP, start ipbench, exit
udhcpc
# cd /usr/ipbench_target/
echo "DHCP leased."
export PYTHONPATH=/usr/lib/python3.10/site-packagesgit 
# echo "Ready for ipbench connection..."
# ipbenchd --target

echo "Awaiting tester connection"
python3 /usr/tester_wait_py/testerwait.py

echo "Beginning iperf3 tests!"


# stolen from https://unix.stackexchange.com/questions/706406/kill-program-if-no-output-to-stdout-for-x-seconds
iperf3 -s > out.txt &
my_prog_pid="$!"
my_watch_status=0

while [ "$my_watch_status" != "2" ]; do
    /usr/bin/inotifywait -qq -t 10 -e modify out.txt 2>/dev/null & 
    wait $!
    my_watch_status="$?"
done

kill -9 "$my_prog_pid"




# this should be unreachable, but this gets us out if iperf crashes
echo "Ostritch"
