#!/bin/sh
# Lease DHCP, start ipbench, exit
udhcpc
# cd /usr/ipbench_target/
echo "DHCP leased."
export PYTHONPATH=/usr/lib/python3.10/site-packages
echo "Ready for ipbench connection..."
# ipbenchd --target
echo "ALL DONE"
